import datetime
today = datetime.date.today()
print(type(today))
print('Today is', today)
print('Today year:', today.year) 
print('Today month:', today.month) 
print('Today day:', today.day) 
print('Today weekday:', today.weekday())
now = datetime.datetime.now()
print(type(now))
print('Now is', now)
print('Now year:', now.year) 
print('Now month:', now.month) 
print('Now day:', now.day) 
print('Now weekday:', now.weekday())
print('Now hour:', now.hour) 
print('Now minute:', now.minute) 
print('Now second:', now.second) 
print('Now microsecond:', now.microsecond) 
print('Now timezone:', now.tzinfo)
dt = datetime.datetime(2023, 12, 31, 23, 59, 59)
print('Custom date time:', dt)

