import numpy as np
# arr1 = np.arange(3)
# print(arr1)
# arr2 = np.arange(3.0)
# print(arr2)
arr3 = np.arange(3, 7)
print(arr3)
# arr4 = np.arange(3,7,2)
# print(arr4)
print(arr3.mean())
print(arr3.std())
print(arr3.sum())
print(arr3.min())
print(arr3.max())
print(arr3.argmin())
print(arr3.argmax())
print(arr3.shape)
print(arr3.dtype)
print(arr3.size)
print(arr3.itemsize)
print(arr3.nbytes)
print(arr3.ndim)
print(arr3.reshape(4, 1))