import numpy as np
arr1 = np.arange(3)
print(arr1)
arr2 = np.arange(3.0)
print(arr2)
arr3 = np.arange(3,7)
print(arr3)
arr4 = np.arange(3, 7, 2)
print(arr4)
print(arr3.mean())
print(arr3.std())
print(arr3.sum())
print(arr3.min())
print(arr3.max())
print(arr4.dtype)
print(arr4.shape)
print(arr4.ndim)
print(arr4.size)